service: todo
provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 2048
  stage: dev
  timeout: 15
  region: us-east-1
  httpApi:
    cors: true
functions:
  graphql:
    handler: index.graphqlHandler
    events:
      - httpApi:
          path: /
          method: POST
      - httpApi:
          path: /
          method: GET
    environment:
      DATABASE_URL: mongodb+srv://thrindle:cdGWXFz4lrPuuBIW@cluster0.jx58dme.mongodb.net/


